// Popular destinations for the search autocomplete, as [place, region/country].
// Roughly ordered by popularity: earlier entries win ties in search results,
// and the first few are shown as suggestions before the user types.
export const DESTINATIONS: readonly (readonly [string, string])[] = [
  ["Paris", "France"],
  ["London", "United Kingdom"],
  ["New York", "New York, United States"],
  ["Tokyo", "Japan"],
  ["Rome", "Italy"],
  ["Barcelona", "Spain"],
  ["Bali", "Indonesia"],
  ["Dubai", "United Arab Emirates"],
  ["Lisbon", "Portugal"],
  ["Amsterdam", "Netherlands"],
  ["Los Angeles", "California, United States"],
  ["Bangkok", "Thailand"],
  ["Istanbul", "Türkiye"],
  ["Singapore", "Singapore"],
  ["Kyoto", "Japan"],
  ["Cancún", "Quintana Roo, Mexico"],
  ["Sydney", "New South Wales, Australia"],
  ["Miami", "Florida, United States"],
  ["Seoul", "South Korea"],
  ["Prague", "Czechia"],
  ["Positano", "Italy"],
  ["Santorini", "Greece"],
  ["Mexico City", "Mexico"],
  ["Madrid", "Spain"],
  ["Honolulu", "Hawaii, United States"],
  ["Las Vegas", "Nevada, United States"],
  ["Reykjavík", "Iceland"],
  ["Vienna", "Austria"],
  ["Berlin", "Germany"],
  ["Florence", "Italy"],
  ["Venice", "Italy"],
  ["Hong Kong", "Hong Kong SAR"],
  ["Marrakesh", "Morocco"],
  ["Cape Town", "South Africa"],
  ["Rio de Janeiro", "Brazil"],
  ["Buenos Aires", "Argentina"],
  ["San Francisco", "California, United States"],
  ["Orlando", "Florida, United States"],
  ["Toronto", "Ontario, Canada"],
  ["Vancouver", "British Columbia, Canada"],
  ["Edinburgh", "Scotland, United Kingdom"],
  ["Dublin", "Ireland"],
  ["Athens", "Greece"],
  ["Budapest", "Hungary"],
  ["Copenhagen", "Denmark"],
  ["Stockholm", "Sweden"],
  ["Oslo", "Norway"],
  ["Helsinki", "Finland"],
  ["Zurich", "Switzerland"],
  ["Geneva", "Switzerland"],
  ["Interlaken", "Switzerland"],
  ["Munich", "Germany"],
  ["Milan", "Italy"],
  ["Naples", "Italy"],
  ["Amalfi Coast", "Italy"],
  ["Lake Como", "Italy"],
  ["Tuscany", "Italy"],
  ["Sicily", "Italy"],
  ["Cinque Terre", "Italy"],
  ["Capri", "Italy"],
  ["Porto", "Portugal"],
  ["Madeira", "Portugal"],
  ["Algarve", "Portugal"],
  ["Seville", "Spain"],
  ["Valencia", "Spain"],
  ["Mallorca", "Balearic Islands, Spain"],
  ["Ibiza", "Balearic Islands, Spain"],
  ["Granada", "Spain"],
  ["Málaga", "Spain"],
  ["San Sebastián", "Spain"],
  ["Tenerife", "Canary Islands, Spain"],
  ["Nice", "France"],
  ["Cannes", "France"],
  ["Lyon", "France"],
  ["Marseille", "France"],
  ["Bordeaux", "France"],
  ["Provence", "France"],
  ["Normandy", "France"],
  ["Loire Valley", "France"],
  ["Strasbourg", "France"],
  ["Chamonix", "France"],
  ["Monaco", "Monaco"],
  ["Mykonos", "Greece"],
  ["Crete", "Greece"],
  ["Dubrovnik", "Croatia"],
  ["Split", "Croatia"],
  ["Kraków", "Poland"],
  ["Warsaw", "Poland"],
  ["Brussels", "Belgium"],
  ["Bruges", "Belgium"],
  ["Salzburg", "Austria"],
  ["Hallstatt", "Austria"],
  ["Zermatt", "Switzerland"],
  ["Lucerne", "Switzerland"],
  ["St. Moritz", "Switzerland"],
  ["Hamburg", "Germany"],
  ["Heidelberg", "Germany"],
  ["Black Forest", "Germany"],
  ["Rotterdam", "Netherlands"],
  ["Luxembourg", "Luxembourg"],
  ["Dolomites", "Italy"],
  ["Bologna", "Italy"],
  ["Verona", "Italy"],
  ["Sardinia", "Italy"],
  ["Tallinn", "Estonia"],
  ["Riga", "Latvia"],
  ["Vilnius", "Lithuania"],
  ["Ljubljana", "Slovenia"],
  ["Lake Bled", "Slovenia"],
  ["Kotor", "Montenegro"],
  ["Belgrade", "Serbia"],
  ["Sarajevo", "Bosnia and Herzegovina"],
  ["Bucharest", "Romania"],
  ["Brașov", "Transylvania, Romania"],
  ["Sofia", "Bulgaria"],
  ["Tirana", "Albania"],
  ["Tbilisi", "Georgia"],
  ["Cappadocia", "Türkiye"],
  ["Antalya", "Türkiye"],
  ["Bodrum", "Türkiye"],
  ["Valletta", "Malta"],
  ["Paphos", "Cyprus"],
  ["Galway", "Ireland"],
  ["Killarney", "Ireland"],
  ["Belfast", "Northern Ireland, United Kingdom"],
  ["Isle of Skye", "Scotland, United Kingdom"],
  ["Scottish Highlands", "Scotland, United Kingdom"],
  ["Bath", "England, United Kingdom"],
  ["Manchester", "England, United Kingdom"],
  ["Cotswolds", "England, United Kingdom"],
  ["Lake District", "England, United Kingdom"],
  ["Cornwall", "England, United Kingdom"],
  ["Cardiff", "Wales, United Kingdom"],
  ["Lofoten Islands", "Norway"],
  ["Tromsø", "Norway"],
  ["Bergen", "Norway"],
  ["Rovaniemi", "Lapland, Finland"],
  ["Tórshavn", "Faroe Islands"],
  ["Chicago", "Illinois, United States"],
  ["Washington, D.C.", "United States"],
  ["Boston", "Massachusetts, United States"],
  ["Seattle", "Washington, United States"],
  ["San Diego", "California, United States"],
  ["New Orleans", "Louisiana, United States"],
  ["Nashville", "Tennessee, United States"],
  ["Austin", "Texas, United States"],
  ["Denver", "Colorado, United States"],
  ["Aspen", "Colorado, United States"],
  ["Park City", "Utah, United States"],
  ["Scottsdale", "Arizona, United States"],
  ["Sedona", "Arizona, United States"],
  ["Grand Canyon", "Arizona, United States"],
  ["Joshua Tree", "California, United States"],
  ["Palm Springs", "California, United States"],
  ["Napa Valley", "California, United States"],
  ["Lake Tahoe", "California, United States"],
  ["Yosemite", "California, United States"],
  ["Maui", "Hawaii, United States"],
  ["Kauai", "Hawaii, United States"],
  ["Key West", "Florida, United States"],
  ["Charleston", "South Carolina, United States"],
  ["Savannah", "Georgia, United States"],
  ["Asheville", "North Carolina, United States"],
  ["Portland", "Oregon, United States"],
  ["Anchorage", "Alaska, United States"],
  ["Philadelphia", "Pennsylvania, United States"],
  ["Atlanta", "Georgia, United States"],
  ["Dallas", "Texas, United States"],
  ["Houston", "Texas, United States"],
  ["Salt Lake City", "Utah, United States"],
  ["Jackson Hole", "Wyoming, United States"],
  ["Martha's Vineyard", "Massachusetts, United States"],
  ["The Hamptons", "New York, United States"],
  ["Montreal", "Quebec, Canada"],
  ["Quebec City", "Quebec, Canada"],
  ["Banff", "Alberta, Canada"],
  ["Whistler", "British Columbia, Canada"],
  ["Calgary", "Alberta, Canada"],
  ["Tulum", "Quintana Roo, Mexico"],
  ["Playa del Carmen", "Quintana Roo, Mexico"],
  ["Cabo San Lucas", "Baja California Sur, Mexico"],
  ["Puerto Vallarta", "Jalisco, Mexico"],
  ["Guadalajara", "Jalisco, Mexico"],
  ["Oaxaca", "Mexico"],
  ["San Miguel de Allende", "Guanajuato, Mexico"],
  ["Havana", "Cuba"],
  ["San Juan", "Puerto Rico"],
  ["Punta Cana", "Dominican Republic"],
  ["Montego Bay", "Jamaica"],
  ["Nassau", "Bahamas"],
  ["Oranjestad", "Aruba"],
  ["Providenciales", "Turks and Caicos Islands"],
  ["Castries", "Saint Lucia"],
  ["Bridgetown", "Barbados"],
  ["San José", "Costa Rica"],
  ["Tamarindo", "Costa Rica"],
  ["Panama City", "Panama"],
  ["Cartagena", "Colombia"],
  ["Medellín", "Colombia"],
  ["Bogotá", "Colombia"],
  ["Lima", "Peru"],
  ["Cusco", "Peru"],
  ["Machu Picchu", "Peru"],
  ["Quito", "Ecuador"],
  ["Galápagos Islands", "Ecuador"],
  ["Santiago", "Chile"],
  ["Patagonia", "Argentina"],
  ["Mendoza", "Argentina"],
  ["São Paulo", "Brazil"],
  ["Florianópolis", "Brazil"],
  ["Montevideo", "Uruguay"],
  ["Osaka", "Japan"],
  ["Sapporo", "Hokkaido, Japan"],
  ["Okinawa", "Japan"],
  ["Hakone", "Japan"],
  ["Nara", "Japan"],
  ["Busan", "South Korea"],
  ["Jeju Island", "South Korea"],
  ["Taipei", "Taiwan"],
  ["Shanghai", "China"],
  ["Beijing", "China"],
  ["Macau", "Macao SAR"],
  ["Hanoi", "Vietnam"],
  ["Ho Chi Minh City", "Vietnam"],
  ["Hoi An", "Vietnam"],
  ["Ha Long Bay", "Vietnam"],
  ["Da Nang", "Vietnam"],
  ["Phuket", "Thailand"],
  ["Chiang Mai", "Thailand"],
  ["Krabi", "Thailand"],
  ["Koh Samui", "Thailand"],
  ["Siem Reap", "Cambodia"],
  ["Luang Prabang", "Laos"],
  ["Kuala Lumpur", "Malaysia"],
  ["Langkawi", "Malaysia"],
  ["Penang", "Malaysia"],
  ["Jakarta", "Indonesia"],
  ["Ubud", "Bali, Indonesia"],
  ["Manila", "Philippines"],
  ["Palawan", "Philippines"],
  ["Boracay", "Philippines"],
  ["Cebu", "Philippines"],
  ["Malé", "Maldives"],
  ["Colombo", "Sri Lanka"],
  ["Kathmandu", "Nepal"],
  ["Mumbai", "India"],
  ["New Delhi", "India"],
  ["Jaipur", "India"],
  ["Goa", "India"],
  ["Agra", "India"],
  ["Kerala", "India"],
  ["Udaipur", "India"],
  ["Abu Dhabi", "United Arab Emirates"],
  ["Doha", "Qatar"],
  ["Muscat", "Oman"],
  ["Petra", "Jordan"],
  ["Amman", "Jordan"],
  ["Tel Aviv", "Israel"],
  ["Jerusalem", "Israel"],
  ["Cairo", "Egypt"],
  ["Luxor", "Egypt"],
  ["Sharm El Sheikh", "Egypt"],
  ["Fes", "Morocco"],
  ["Chefchaouen", "Morocco"],
  ["Zanzibar", "Tanzania"],
  ["Serengeti", "Tanzania"],
  ["Nairobi", "Kenya"],
  ["Maasai Mara", "Kenya"],
  ["Kigali", "Rwanda"],
  ["Victoria Falls", "Zimbabwe"],
  ["Johannesburg", "South Africa"],
  ["Port Louis", "Mauritius"],
  ["Mahé", "Seychelles"],
  ["Melbourne", "Victoria, Australia"],
  ["Brisbane", "Queensland, Australia"],
  ["Gold Coast", "Queensland, Australia"],
  ["Cairns", "Queensland, Australia"],
  ["Perth", "Western Australia, Australia"],
  ["Adelaide", "South Australia, Australia"],
  ["Hobart", "Tasmania, Australia"],
  ["Auckland", "New Zealand"],
  ["Queenstown", "New Zealand"],
  ["Wellington", "New Zealand"],
  ["Rotorua", "New Zealand"],
  ["Nadi", "Fiji"],
  ["Bora Bora", "French Polynesia"],
  ["Tahiti", "French Polynesia"],
];

// Homepage "Popular destinations": five ranked places per tab, each with the
// little scene its tile draws and a pastel gradient. "Near you" is a fixed
// California list until the site knows where the guest is.
export type DestinationScene = "coast" | "lake" | "beach" | "mountain" | "city";
export type PopularDestination = { name: string; region: string; scene: DestinationScene; colors: [string, string] };
export type DestinationTab = "near" | "national" | "international";

export const POPULAR_TABS: { id: DestinationTab; label: string }[] = [
  { id: "near", label: "Near you" },
  { id: "national", label: "National" },
  { id: "international", label: "International" },
];

export const POPULAR_DESTINATIONS: Record<DestinationTab, PopularDestination[]> = {
  near: [
    { name: "Monterey", region: "California, United States", scene: "coast", colors: ["#86ade6", "#cfe0f7"] },
    { name: "Lake Tahoe", region: "California, United States", scene: "lake", colors: ["#8cc3cc", "#d3ecee"] },
    { name: "Santa Cruz", region: "California, United States", scene: "beach", colors: ["#f0b39e", "#fbe1d0"] },
    { name: "Big Sur", region: "California, United States", scene: "mountain", colors: ["#a9a0e2", "#dcd6f6"] },
    { name: "San Francisco", region: "California, United States", scene: "city", colors: ["#eeaec3", "#f9dde6"] },
    { name: "Carmel-by-the-Sea", region: "California, United States", scene: "beach", colors: ["#86c2d8", "#d2ebf3"] },
    { name: "Yosemite", region: "California, United States", scene: "mountain", colors: ["#8fb4e8", "#d5e4f8"] },
    { name: "Mendocino", region: "California, United States", scene: "coast", colors: ["#f2bda6", "#fbe5d6"] },
  ],
  national: [
    { name: "New York", region: "New York, United States", scene: "city", colors: ["#a3a8e6", "#d8daf7"] },
    { name: "Honolulu", region: "Hawaii, United States", scene: "beach", colors: ["#86c2d8", "#d2ebf3"] },
    { name: "Aspen", region: "Colorado, United States", scene: "mountain", colors: ["#8fb4e8", "#d5e4f8"] },
    { name: "Seattle", region: "Washington, United States", scene: "coast", colors: ["#b5a4e0", "#e2d9f5"] },
    { name: "Lake Placid", region: "New York, United States", scene: "lake", colors: ["#f2bda6", "#fbe5d6"] },
    { name: "Miami", region: "Florida, United States", scene: "beach", colors: ["#eeaec3", "#f9dde6"] },
    { name: "Sedona", region: "Arizona, United States", scene: "mountain", colors: ["#f0b39e", "#fbe1d0"] },
    { name: "Chicago", region: "Illinois, United States", scene: "city", colors: ["#8cc3cc", "#d3ecee"] },
  ],
  international: [
    { name: "Positano", region: "Italy", scene: "coast", colors: ["#f0b39e", "#fbe1d0"] },
    { name: "Kyoto", region: "Japan", scene: "city", colors: ["#eeaec3", "#f9dde6"] },
    { name: "Reykjavík", region: "Iceland", scene: "mountain", colors: ["#8cc3cc", "#d3ecee"] },
    { name: "Santorini", region: "Greece", scene: "beach", colors: ["#86ade6", "#cfe0f7"] },
    { name: "Lucerne", region: "Switzerland", scene: "lake", colors: ["#a9a0e2", "#dcd6f6"] },
    { name: "Lisbon", region: "Portugal", scene: "city", colors: ["#a3a8e6", "#d8daf7"] },
    { name: "Bali", region: "Indonesia", scene: "beach", colors: ["#86c2d8", "#d2ebf3"] },
    { name: "Banff", region: "Alberta, Canada", scene: "mountain", colors: ["#8fb4e8", "#d5e4f8"] },
  ],
};
